version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.3.7
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Run test
          command: ruby calculation_spec.rb

workflows:
  version: 2
  workflows:
    jobs:
      - test